# Generated by Django 5.2.9 on 2025-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
