# Generated by Django 5.2.9 on 2025-12-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tarefa_prazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
    ]
