# Generated by Django 5.2.9 on 2025-12-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tarefa_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
    ]
